### ISSUE TITLE
Styling problemer ved oppsøkte produkter

### ISSUE THREAD

**Issue by JimAlexBerger** [matslb/Spritjakt.no#1]
Kan gjennskapes ved f.eks. å søke på "amarone", deretter trykke på et av produktene som kommer opp.
Når man scroller nedover på siden havner de eldre elementene over modalen som dukker opp.

![image](https://user-images.githubusercontent.com/13706770/90013212-22d01c00-dca5-11ea-8113-bb142bf7894b.png)

**Comment by matslb** [comment]
Takker! Er fiksa nå
