### ISSUE TITLE
Vise tilgjengelighet på valgt butikk

### ISSUE THREAD

**Issue by nwinger** [matslb/Spritjakt.no#2]
Bare en liten feature request til et kult produkt! Vet ikke om API'et tillater det, men om mulig hadde det vært nyttig med en oversikt over hvem som har det aktuelle produktet inne i butikk 😀

**Comment by matslb** [comment]
Nå viser jeg samlet lagerstatus på butikk og på nett, fordi det var alt jeg fikk fra API'et, men jeg fant faktisk et endepunkt som polet selv bruker på sine nettsider for å hente lagerstatus per butikk. Holder på med funksjonen nå :)
