### ISSUE TITLE
Varslinger?

### ISSUE THREAD

**Issue by AndersLokke** [matslb/Spritjakt.no#3]
Fantastisk løsning du har laget :) Et lite prosjektforslag - kanskje du kunne legge til mulighet for registrering av bruker med tilhørende varslinger, slik at om det f.eks kommer produkter enten på navn eller kategori ("Ringnes Julebokk") eller ("øl") i valgt(e) favorittbutikk(er) får man en varsling enten via e-post eller SMS? Jeg hadde gladelig registrert meg med det samme!

mvh,
AndersL

**Comment by matslb** [comment]
Gikk for en enklere løsning med epostadresser, den er live nå :)
