### ISSUE TITLE
Wrong text displayed in the shop selector. 

### ISSUE THREAD

**Issue by stianlarsen** [matslb/Spritjakt.no#4]
![image](https://user-images.githubusercontent.com/19903802/90772867-6d7d1400-e2f5-11ea-8f72-b0f4cdc4a5a3.png)

A bit tricky to reproduce but this sequence of steps reproduces the bug now:

1. Open spritjakt.no
2. Select filter "Rødvin"
3. Select Butikk [Fredrikstad, Østsiden]
4. Select Tidsperiode [Siste 14 dager]

The Butikk selector shows the attached image.

**Comment by matslb** [comment]
Fixed :)
