### ISSUE TITLE
Filtrere på varer som er bestillbare til post/på dør? 

### ISSUE THREAD

**Issue by stianlarsen** [matslb/Spritjakt.no#5]
Det hadde vært supert med et filter for varer som var bestillbare på post/dør. Altså de som ser sånn her ut på vinmonopolets sider:
![image](https://user-images.githubusercontent.com/19903802/91036533-ca374200-e607-11ea-94ac-c80180fcfe48.png)

**Comment by matslb** [comment]
Godt forslag! Slenger inn et filter på lagerstatus
