### ISSUE TITLE
Til gang til data

### ISSUE THREAD

**Issue by muravals** [matslb/Spritjakt.no#6]
Hei, Vinmonopolet endret regler for tilgang til APIer, ikke sant? Åpne APIer har begrenset tilgang nå. Jeg ser at det kommer oppdateringer på websiden. Har du fått tilgang til APIer for pressen/media?

**Comment by matslb** [comment]
Det stemmer. De har endret API'et slik at man ikke lenger får pris og lagerstatus via api.vinmonopolet.no. Men man kan fremdeles hente ut nylig endrede produkter ved å sette changedSince, og det ser ut som om prisendring også gjelder. 
Så jeg henter ut en liste over alle nylig endrede produkter, og bruker Id'ene til å skrape pris og detaljer fra vinmonopolet.no. 
Det tar litt lenger tid, men ser ut til å virke greit.

**Comment by muravals** [comment]
Flott, takk for svaret! Men hvordan skraper du pris og andre opplysninger fra VM websider?

**Comment by matslb** [comment]
vinmonopolet.no kjører også React, så de har et eget API hvor de henter ut produktdata ved page load. eks: https://www.vinmonopolet.no/api/products/358302?fields=FULL
Får det pakket og klart i Json

**Comment by muravals** [comment]
Supert! Takk! Har de samme API for varebeholdning?

**Comment by matslb** [comment]
Den er litt mer vrien for ikke alle parametere i requesten blir brukt, men i utgangspunktet, ja. 
https://www.vinmonopolet.no/api/products/4909804/stock?pageSize=10&currentPage=5&fields=BASIC&latitude=59&longitude=10

**Comment by muravals** [comment]
Så kjekt! Utrolig! Hvor finner du alt dette?

**Comment by matslb** [comment]
Mye leting ;)
